services:
    commerce-api:
        image: registry.digitalocean.com/sleepykoala/commerce
        init: true
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.commerce-api.rule=Host(`commerce.bahanbakarnasi.cloud`)"
            - "traefik.http.routers.commerce-api.entrypoints=websecure"
            - "traefik.http.routers.commerce-api.tls.certresolver=myresolver"
            - "traefik.http.services.commerce-api.loadbalancer.server.port=8080"
        entrypoint: "/app/docker-entrypoint.sh"
        command: ["/app/main"]
        networks:
            - traefik_default
            - commerce-network
networks:
    traefik_default:
        external: true
    commerce-network:
        external: true
