name: backend deployment
on:
    push:
        branches:
            - main
        paths:
            - "backend/**"
            - ".github/workflows/deploy-be.yml"
defaults:
    run:
        working-directory: ./backend
jobs:
    backend-deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: authenticate gcp
              uses: "google-github-actions/auth@v2"
              with:
                  service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

            - name: retrieve secrets from secret managers
              uses: "google-github-actions/get-secretmanager-secrets@v2"
              run: |
                  chmod +x ./scripts/fetch-secrets.sh
                  bash ./scripts/fetch-secrets.sh

            - name: build container image
              run: docker build -t commerce:$(echo $GITHUB_SHA | head -c7) .

            - name: login to digital ocean container registry
              run: doctl registry login --expire-seconds 2400

            - name: push image to registry
              run: docker push ${{ secrets.REGISTRY_NAME }}/commerce:$(echo $GITHUB_SHA | head -c7)

            - name: exec remote ssh
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  passphrase: ${{ secrets.PASSPHRASE }}
                  port: 22
                  script: |
                      cd commerce/backend/
                      docker compose down
                      git pull origin main
                      docker compose up --build --detach commerce_api
