name: backend deployment
on:
    push:
        branches:
            - main
        paths:
            - "backend/**"
            - ".github/workflows/deploy-be.yml"
defaults:
    run:
        working-directory: ./backend
jobs:
    backend-deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: install doctl.
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            - name: authenticate gcp.
              uses: "google-github-actions/auth@v2"
              with:
                  credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
            - name: setup cloud sdk.
              uses: "google-github-actions/setup-gcloud@v2"
            - name: retrieve secrets from secret manager.
              run: |
                  chmod +x ./scripts/fetch-secrets.sh
                  bash ./scripts/fetch-secrets.sh
            - name: build container image.
              run: docker build -t ${{ secrets.REGISTRY_NAME }}/commerce:$(echo $GITHUB_SHA | head -c7) .
            - name: login to digitalocean container registry.
              run: doctl registry login
            - name: push image to registry.
              run: docker push ${{ secrets.REGISTRY_NAME }}/commerce:$(echo $GITHUB_SHA | head -c7)
            - name: exec remote ssh.
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  passphrase: ${{ secrets.PASSPHRASE }}
                  port: 22
                  script: |
                      cd commerce/backend/
                      docker compose down
                      git pull origin main
                      docker compose up --build --detach commerce-api
